services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - backend
      - ml
    networks:
      - appnet
    ports:
      - "7000:7000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - ml
    networks:
      - appnet
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - appnet
    ports:
      - "3000:3000"

  ml:
    build:
      context: ./machine-learning
      dockerfile: Dockerfile
    container_name: machine-learning
    networks:
      - appnet
    ports:
      - "5000:5000"

networks:
  appnet:
    driver: bridge
