version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ml
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

  ml:
    build: ./machine-learning
    container_name: machine-learning
    ports:
      - "5000:5000"
    networks:
      - appnet

  app:
    build: ./app
    container_name: app
    ports:
      - "7000:7000"
    depends_on:
      - backend
      - ml
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

